### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by janprikryl1** [spseol/naavyk#1]
Po přihlášení:
![image](https://user-images.githubusercontent.com/49918221/97674967-b76d3d80-1a8e-11eb-8938-3dace41c424d.png)

**Comment by chazp246** [comment]
Mám to samý.

**Comment by MarrekNozka** [comment]
To je tím, že se mi tam zatím nehlásil žádný student...
Změnil jsem ve zdrojáku jedno písmenko. To jsem zvědav, co tam bude za další problém. 7b7b79df52b58499b10383c03fb7eb483c92772a
Ověřte prosím, že to funguje.
